apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.elasticsearch.instanceName }}
spec:
  version: {{ .Values.elasticsearch.version }}
  auth:
    fileRealm:
    - secretName: {{ .Values.elasticsearch.authSecretName }}
  nodeSets:
  - name: default
    count: {{ .Values.elasticsearch.replicas }}
    config:
      node.store.allow_mmap: false
